services:
  elasticsearch:
    build:
      context: .

    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true

      # ── HTTP TLS ────────────────────────────────────────────
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.certificate_authorities=${ES_CERTS_DIR}/ca/ca.crt
      - xpack.security.http.ssl.certificate=${ES_CERTS_DIR}/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.key=${ES_CERTS_DIR}/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.certificate_authorities=${ES_CERTS_DIR}/ca/ca.crt
      - xpack.security.transport.ssl.certificate=${ES_CERTS_DIR}/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.key=${ES_CERTS_DIR}/elasticsearch/elasticsearch.key
    ports:
      - "9200:9200"
    volumes:
      - ./src/main/resources/certs:${ES_CERTS_DIR:-/usr/share/elasticsearch/config/certs}:ro
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -s -f https://localhost:9200/_cluster/health --cacert ${ES_CERTS_DIR}/ca/ca.crt || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 6

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      # ES 접속 정보 (https 필수)
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${KB_CERTS_DIR}/ca/ca.crt

      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=${KB_CERTS_DIR}/kibana/kibana.crt
      - SERVER_SSL_KEY=${KB_CERTS_DIR}/kibana/kibana.key
    ports:
      - "5601:5601"
    volumes:
      - ./src/main/resources/certs:${KB_CERTS_DIR:-/usr/share/kibana/config/certs}:ro

volumes:
  esdata:
