services:
  elasticsearch:
    build:
      context: .

    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true

      # ── HTTP TLS ────────────────────────────────────────────
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.certificate=/etc/es-certs/fullchain.pem
      - xpack.security.http.ssl.key=/etc/es-certs/privkey.pem

      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate=/etc/es-certs/fullchain.pem
      - xpack.security.transport.ssl.key=/etc/es-certs/privkey.pem
      - xpack.security.transport.ssl.certificate_authorities=/etc/es-certs/fullchain.pem
    ports:
      - "9200:9200"
    volumes:
      - /opt/es-certs:/etc/es-certs:ro
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f https://localhost:9200/_cluster/health --cacert /etc/es-certs/fullchain.pem || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 6

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      # ES 접속 정보 (https 필수)
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/etc/kibana-certs/fullchain.pem
      - SERVER_SSL_KEY=/etc/kibana-certs/privkey.pem
    ports:
      - "5601:5601"
    volumes:
      - /opt/kibana-certs:/etc/kibana-certs:ro

volumes:
  esdata:
