services:
  debug:
    image: alpine:latest
    env_file: ./.env
    command: sh -c "echo '--- Container Environment Variables ---'; printenv | grep ELASTIC; printenv | grep KIBANA; echo '--- End of Test ---'"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    env_file: ./.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      
      # HTTP SSL 설정
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/fullchain.pem
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/privkey.pem
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/fullchain.pem
      
      # Transport SSL 설정
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/fullchain.pem
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/privkey.pem
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/fullchain.pem
    ports:
      - "9200:9200"
    volumes:
      - /opt/es-certs:/usr/share/elasticsearch/config/certs:ro
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k -f https://localhost:9200/_cluster/health --user elastic:${ELASTIC_PASSWORD} || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 6
    networks:
      elastic-net:
        ipv4_address: 172.20.0.10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file: ./.env
    environment:
      - NODE_OPTIONS=--no-openssl-legacy-provider
      
      # Elasticsearch 연결 설정
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/elasticsearch/config/certs/fullchain.pem
      
      # Kibana 서버 SSL 설정
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/etc/kibana-certs/fullchain.pem
      - SERVER_SSL_KEY=/etc/kibana-certs/privkey.pem
      
      # Kibana 암호화 키 설정
      - xpack.security.encryptionKey=${KIBANA_SECURITY_KEY}
      - xpack.encryptedSavedObjects.encryptionKey=${KIBANA_SAVEDOBJECTS_KEY}
      - xpack.reporting.encryptionKey=${KIBANA_REPORTING_KEY}
    ports:
      - "5601:5601"
    volumes:
      - /opt/kibana-certs:/etc/kibana-certs:ro
      - /opt/es-certs:/usr/share/elasticsearch/config/certs:ro
    networks:
      - elastic-net

volumes:
  esdata:

networks:
  elastic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16