services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: song-be
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS:-0.0.0.0}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      PROD_MYSQL_URL: ${PROD_MYSQL_URL}
      PROD_MYSQL_USERNAME: ${PROD_MYSQL_USERNAME}
      PROD_MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PROD_ELASTICSEARCH_URIS: ${PROD_ELASTICSEARCH_URIS}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
